import '../../data/models/customer_model.dart';
import '../../data/models/feed_product_model.dart';
import '../../data/models/medicine_model.dart';
import '../../data/models/order_model.dart';
import '../../data/models/sale_model.dart';
import '../database/hive_service.dart';
import '../database/hive_boxes.dart';

/// Service for seeding initial data into the database
/// 
/// This service populates the database with sample data when
/// the app is first launched or when the database is empty.
class DataSeeder {
  /// Check if database needs seeding
  static bool get needsSeeding {
    return HiveService.customersBox.isEmpty &&
        HiveService.feedProductsBox.isEmpty &&
        HiveService.medicinesBox.isEmpty;
  }

  /// Seed all initial data
  static Future<void> seedAll() async {
    if (!needsSeeding) return;

    await seedCustomers();
    await seedFeedProducts();
    await seedMedicines();
    await seedOrders();
    await seedSales();

    // Mark first launch as complete
    await HiveService.settingsBox.put(SettingsKeys.isFirstLaunch, false);
  }

  /// Seed customer data
  static Future<void> seedCustomers() async {
    final customers = [
      CustomerModel(
        id: 'c1',
        name: 'Anita Mehra',
        shopName: 'Green Pastures Dairy',
        phone: '+91 98200 12345',
        address: 'Nashik, Maharashtra',
        balance: 45200,
        customerType: 'Wholesale',
        createdAt: DateTime.now().subtract(const Duration(days: 90)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c2',
        name: 'Rahul Patil',
        shopName: 'Sunrise Poultry',
        phone: '+91 98333 90876',
        address: 'Kolhapur, Maharashtra',
        balance: -5000,
        customerType: 'Wholesale',
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c3',
        name: 'Maya Dutta',
        shopName: 'Riverdale Fisheries',
        phone: '+91 98111 77722',
        address: 'Karwar, Karnataka',
        balance: 22000,
        customerType: 'VIP',
        createdAt: DateTime.now().subtract(const Duration(days: 120)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c4',
        name: 'Karan Yadav',
        shopName: 'Silver Goat Farm',
        phone: '+91 98700 66771',
        address: 'Indore, MP',
        balance: 8200,
        customerType: 'Retail',
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c5',
        name: 'Sonia Bedi',
        shopName: 'Bluebell Kennels',
        phone: '+91 99588 54323',
        address: 'Chandigarh',
        balance: 3400,
        customerType: 'Retail',
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c6',
        name: 'Pranav Joshi',
        shopName: 'AgroPlus Retail',
        phone: '+91 97979 11100',
        address: 'Ahmednagar, Maharashtra',
        balance: -18000,
        customerType: 'Wholesale',
        createdAt: DateTime.now().subtract(const Duration(days: 75)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c7',
        name: 'Devika Nair',
        shopName: 'Hillside Dairy',
        phone: '+91 97777 67890',
        address: 'Munnar, Kerala',
        balance: 15600,
        customerType: 'Wholesale',
        createdAt: DateTime.now().subtract(const Duration(days: 100)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c8',
        name: 'Siddharth Prasad',
        shopName: 'Urban Vet Care',
        phone: '+91 99666 44220',
        address: 'Hyderabad, Telangana',
        balance: 9600,
        customerType: 'VIP',
        createdAt: DateTime.now().subtract(const Duration(days: 55)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c9',
        name: 'Bhavna Iyer',
        shopName: 'Lotus Equine',
        phone: '+91 99812 89345',
        address: 'Pune, Maharashtra',
        balance: 45200,
        customerType: 'VIP',
        createdAt: DateTime.now().subtract(const Duration(days: 150)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      CustomerModel(
        id: 'c10',
        name: 'Jatin Kumar',
        shopName: 'Healthy Herds',
        phone: '+91 98564 32100',
        address: 'Nagpur, Maharashtra',
        balance: -2400,
        customerType: 'Retail',
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
    ];

    final box = HiveService.customersBox;
    for (final customer in customers) {
      await box.put(customer.id, customer);
    }
  }

  /// Seed feed product data
  static Future<void> seedFeedProducts() async {
    final products = [
      FeedProductModel(
        id: 'fp1',
        name: 'Premium Dairy Feed',
        category: 'Cattle',
        image: 'https://picsum.photos/seed/feed1/400/400',
        unit: 'kg',
        stock: 140,
        lowStockThreshold: 60,
        rate: 1200,
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp2',
        name: 'Broiler Starter',
        category: 'Poultry',
        image: 'https://picsum.photos/seed/feed2/400/400',
        unit: 'kg',
        stock: 80,
        lowStockThreshold: 50,
        rate: 980,
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp3',
        name: 'Goat Grower Mix',
        category: 'Goat',
        image: 'https://picsum.photos/seed/feed3/400/400',
        unit: 'kg',
        stock: 45,
        lowStockThreshold: 40,
        rate: 1350,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp4',
        name: 'Layer Mash',
        category: 'Poultry',
        image: 'https://picsum.photos/seed/feed4/400/400',
        unit: 'kg',
        stock: 210,
        lowStockThreshold: 90,
        rate: 870,
        createdAt: DateTime.now().subtract(const Duration(days: 55)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp5',
        name: 'Floating Fish Feed',
        category: 'Fish',
        image: 'https://picsum.photos/seed/feed5/400/400',
        unit: 'kg',
        stock: 25,
        lowStockThreshold: 40,
        rate: 1650,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp6',
        name: 'Mineral Mix',
        category: 'Supplements',
        image: 'https://picsum.photos/seed/feed6/400/400',
        unit: 'kg',
        stock: 95,
        lowStockThreshold: 30,
        rate: 760,
        createdAt: DateTime.now().subtract(const Duration(days: 40)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp7',
        name: 'Calf Starter',
        category: 'Cattle',
        image: 'https://picsum.photos/seed/feed7/400/400',
        unit: 'kg',
        stock: 132,
        lowStockThreshold: 55,
        rate: 1450,
        createdAt: DateTime.now().subtract(const Duration(days: 35)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp8',
        name: 'Duck Grower',
        category: 'Poultry',
        image: 'https://picsum.photos/seed/feed8/400/400',
        unit: 'kg',
        stock: 68,
        lowStockThreshold: 35,
        rate: 910,
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp9',
        name: 'Sheep Finisher',
        category: 'Goat',
        image: 'https://picsum.photos/seed/feed9/400/400',
        unit: 'kg',
        stock: 33,
        lowStockThreshold: 30,
        rate: 1180,
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp10',
        name: 'Premium Probiotic',
        category: 'Supplements',
        image: 'https://picsum.photos/seed/feed10/400/400',
        unit: 'kg',
        stock: 58,
        lowStockThreshold: 25,
        rate: 2100,
        createdAt: DateTime.now().subtract(const Duration(days: 50)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp11',
        name: 'Organic Layer Boost',
        category: 'Premium',
        image: 'https://picsum.photos/seed/feed11/400/400',
        unit: 'kg',
        stock: 70,
        lowStockThreshold: 40,
        rate: 1950,
        createdAt: DateTime.now().subtract(const Duration(days: 28)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      FeedProductModel(
        id: 'fp12',
        name: 'Aqua Supreme',
        category: 'Fish',
        image: 'https://picsum.photos/seed/feed12/400/400',
        unit: 'kg',
        stock: 45,
        lowStockThreshold: 30,
        rate: 1750,
        createdAt: DateTime.now().subtract(const Duration(days: 22)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
    ];

    final box = HiveService.feedProductsBox;
    for (final product in products) {
      await box.put(product.id, product);
    }
  }

  /// Seed medicine data
  static Future<void> seedMedicines() async {
    final now = DateTime.now();
    final medicines = [
      MedicineModel(
        id: 'm1',
        name: 'VetAmox 500',
        genericName: 'Amoxicillin',
        category: 'Antibiotic',
        image: 'https://picsum.photos/seed/med1/500/500',
        batchNo: 'AMX2024A',
        mfgDate: DateTime(2024, 4, 10),
        expiryDate: DateTime(2026, 4, 9),
        manufacturer: 'Wellness Labs',
        purchasePrice: 180,
        sellingPrice: 280,
        discount: 5,
        quantity: 240,
        minStockLevel: 120,
        unit: 'strips',
        storage: 'Store below 25°C, protect from light',
        description: 'Broad spectrum antibiotic for severe infections.',
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm2',
        name: 'NeoVita Boost',
        genericName: 'Multivitamin',
        category: 'Vitamin',
        image: 'https://picsum.photos/seed/med2/500/500',
        batchNo: 'NVB024',
        mfgDate: DateTime(2024, 2, 14),
        expiryDate: DateTime(2025, 8, 13),
        manufacturer: 'NutriVet',
        purchasePrice: 95,
        sellingPrice: 160,
        discount: 10,
        quantity: 320,
        minStockLevel: 150,
        unit: 'bottles',
        storage: 'Refrigerate after opening',
        description: 'Daily vitamin tonic for livestock immunity.',
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm3',
        name: 'HelmEx Plus',
        genericName: 'Albendazole',
        category: 'Dewormer',
        image: 'https://picsum.photos/seed/med3/500/500',
        batchNo: 'HEX881',
        mfgDate: DateTime(2023, 11, 1),
        expiryDate: DateTime(2025, 4, 30),
        manufacturer: 'PrimeVet',
        purchasePrice: 120,
        sellingPrice: 210,
        discount: 8,
        quantity: 110,
        minStockLevel: 120,
        unit: 'packs',
        storage: 'Store at room temperature',
        description: 'Fast acting dewormer for cattle & goats.',
        createdAt: now.subtract(const Duration(days: 90)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm4',
        name: 'Respira Shield',
        genericName: 'Tylosin',
        category: 'Antibiotic',
        image: 'https://picsum.photos/seed/med4/500/500',
        batchNo: 'RS731',
        mfgDate: DateTime(2023, 9, 22),
        expiryDate: DateTime(2025, 3, 21),
        manufacturer: 'Airway Labs',
        purchasePrice: 205,
        sellingPrice: 320,
        discount: 12,
        quantity: 95,
        minStockLevel: 80,
        unit: 'vials',
        storage: 'Keep sealed until use',
        description: 'Respiratory infection management for poultry.',
        createdAt: now.subtract(const Duration(days: 120)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm5',
        name: 'LactoGuard',
        genericName: 'Probiotic blend',
        category: 'Supplement',
        image: 'https://picsum.photos/seed/med5/500/500',
        batchNo: 'LG554',
        mfgDate: DateTime(2024, 1, 18),
        expiryDate: DateTime(2025, 12, 17),
        manufacturer: 'Green Cow',
        purchasePrice: 150,
        sellingPrice: 240,
        discount: 6,
        quantity: 200,
        minStockLevel: 90,
        unit: 'sachets',
        storage: 'Store in dry cool place',
        description: 'Improves milk yield and digestion.',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm6',
        name: 'ImmuShield V',
        genericName: 'FMD Vaccine',
        category: 'Vaccine',
        image: 'https://picsum.photos/seed/med6/500/500',
        batchNo: 'IMV997',
        mfgDate: DateTime(2024, 5, 5),
        expiryDate: DateTime(2025, 5, 4),
        manufacturer: 'Guardian Bio',
        purchasePrice: 260,
        sellingPrice: 420,
        discount: 0,
        quantity: 60,
        minStockLevel: 70,
        unit: 'doses',
        storage: 'Cold chain 2-8°C',
        description: 'Foot-and-mouth disease vaccine.',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm7',
        name: 'CalmHoof Relief',
        genericName: 'Meloxicam',
        category: 'Pain Relief',
        image: 'https://picsum.photos/seed/med7/500/500',
        batchNo: 'CHR205',
        mfgDate: DateTime(2023, 12, 2),
        expiryDate: DateTime(2025, 11, 30),
        manufacturer: 'Relievex',
        purchasePrice: 140,
        sellingPrice: 230,
        discount: 4,
        quantity: 140,
        minStockLevel: 75,
        unit: 'vials',
        storage: 'Protect from sunlight',
        description: 'Anti inflammatory for lameness pain.',
        createdAt: now.subtract(const Duration(days: 75)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm8',
        name: 'AquaCare Shield',
        genericName: 'Oxytetracycline',
        category: 'Antibiotic',
        image: 'https://picsum.photos/seed/med8/500/500',
        batchNo: 'ACS584',
        mfgDate: DateTime(2023, 10, 11),
        expiryDate: DateTime(2025, 2, 10),
        manufacturer: 'Oceanic',
        purchasePrice: 115,
        sellingPrice: 205,
        discount: 9,
        quantity: 70,
        minStockLevel: 60,
        unit: 'litres',
        storage: 'Store in original container',
        description: 'For fish pond bacterial outbreaks.',
        createdAt: now.subtract(const Duration(days: 100)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm9',
        name: 'ProtoX Clear',
        genericName: 'Metronidazole',
        category: 'Antibiotic',
        image: 'https://picsum.photos/seed/med9/500/500',
        batchNo: 'PX112',
        mfgDate: DateTime(2024, 3, 8),
        expiryDate: DateTime(2026, 3, 7),
        manufacturer: 'NexGen Vet',
        purchasePrice: 95,
        sellingPrice: 170,
        discount: 7,
        quantity: 310,
        minStockLevel: 140,
        unit: 'tablets',
        storage: 'Store below 30°C',
        description: 'Protozoal infections in pets & livestock.',
        createdAt: now.subtract(const Duration(days: 40)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm10',
        name: 'HoofFlex Gold',
        genericName: 'Biotin blend',
        category: 'Supplement',
        image: 'https://picsum.photos/seed/med10/500/500',
        batchNo: 'HFG889',
        mfgDate: DateTime(2023, 8, 15),
        expiryDate: DateTime(2025, 8, 14),
        manufacturer: 'Stride Plus',
        purchasePrice: 175,
        sellingPrice: 285,
        discount: 6,
        quantity: 85,
        minStockLevel: 50,
        unit: 'tubs',
        storage: 'Store sealed, dry location',
        description: 'Hoof strength supplement for equines.',
        createdAt: now.subtract(const Duration(days: 150)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm11',
        name: 'Dermaclean Spray',
        genericName: 'Chlorhexidine',
        category: 'Antibiotic',
        image: 'https://picsum.photos/seed/med11/500/500',
        batchNo: 'DCS640',
        mfgDate: DateTime(2024, 6, 1),
        expiryDate: DateTime(2026, 5, 31),
        manufacturer: 'SkinGuard',
        purchasePrice: 88,
        sellingPrice: 155,
        discount: 5,
        quantity: 260,
        minStockLevel: 120,
        unit: 'bottles',
        storage: 'Store at 25°C max',
        description: 'Topical antiseptic for wounds.',
        createdAt: now.subtract(const Duration(days: 15)),
        updatedAt: now,
        isSynced: true,
      ),
      MedicineModel(
        id: 'm12',
        name: 'ElectroFit Max',
        genericName: 'Electrolyte mix',
        category: 'Supplement',
        image: 'https://picsum.photos/seed/med12/500/500',
        batchNo: 'EFM221',
        mfgDate: DateTime(2024, 2, 22),
        expiryDate: DateTime(2025, 9, 21),
        manufacturer: 'HydroVet',
        purchasePrice: 110,
        sellingPrice: 190,
        discount: 5,
        quantity: 180,
        minStockLevel: 80,
        unit: 'sachets',
        storage: 'Keep sealed',
        description: 'Rapid rehydration for stressed animals.',
        createdAt: now.subtract(const Duration(days: 35)),
        updatedAt: now,
        isSynced: true,
      ),
    ];

    final box = HiveService.medicinesBox;
    for (final medicine in medicines) {
      await box.put(medicine.id, medicine);
    }
  }

  /// Seed order data
  static Future<void> seedOrders() async {
    final orders = [
      OrderModel(
        id: 'o1',
        customerId: 'c1',
        customerName: 'Anita Mehra',
        orderNumber: '#FD-1023',
        date: DateTime.now().subtract(const Duration(days: 1)),
        subtotal: 142000,
        discount: 7000,
        total: 135000,
        paymentStatus: 'Paid',
        orderType: 'feed',
        items: [],
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      OrderModel(
        id: 'o2',
        customerId: 'c3',
        customerName: 'Maya Dutta',
        orderNumber: '#FD-1024',
        date: DateTime.now(),
        subtotal: 45000,
        discount: 2000,
        total: 43000,
        paymentStatus: 'Pending',
        orderType: 'feed',
        items: [],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      OrderModel(
        id: 'o3',
        customerId: 'c4',
        customerName: 'Karan Yadav',
        orderNumber: '#FD-1025',
        date: DateTime.now().subtract(const Duration(days: 1)),
        subtotal: 61200,
        discount: 2500,
        total: 58700,
        paymentStatus: 'Partially Paid',
        orderType: 'feed',
        items: [],
        paidAmount: 30000,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      OrderModel(
        id: 'o4',
        customerId: 'c2',
        customerName: 'Rahul Patil',
        orderNumber: '#FD-1026',
        date: DateTime.now().subtract(const Duration(days: 2)),
        subtotal: 28800,
        discount: 1000,
        total: 27800,
        paymentStatus: 'Paid',
        orderType: 'feed',
        items: [],
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      OrderModel(
        id: 'o5',
        customerId: 'c5',
        customerName: 'Sonia Bedi',
        orderNumber: '#FD-1027',
        date: DateTime.now().subtract(const Duration(days: 2)),
        subtotal: 72000,
        discount: 2500,
        total: 69500,
        paymentStatus: 'Pending',
        orderType: 'feed',
        items: [],
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
    ];

    final box = HiveService.ordersBox;
    for (final order in orders) {
      await box.put(order.id, order);
    }
  }

  /// Seed sales data
  static Future<void> seedSales() async {
    final sales = [
      SaleModel(
        id: 's1',
        billNumber: '#MD-2211',
        date: DateTime.now().subtract(const Duration(days: 1)),
        subtotal: 88000,
        discount: 3200,
        total: 84800,
        profit: 22000,
        items: [],
        paymentMethod: 'Cash',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      SaleModel(
        id: 's2',
        billNumber: '#MD-2212',
        date: DateTime.now().subtract(const Duration(days: 1)),
        subtotal: 62000,
        discount: 2000,
        total: 60000,
        profit: 14500,
        items: [],
        paymentMethod: 'UPI',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      SaleModel(
        id: 's3',
        billNumber: '#MD-2213',
        date: DateTime.now().subtract(const Duration(days: 2)),
        subtotal: 45000,
        discount: 1800,
        total: 43200,
        profit: 11000,
        items: [],
        paymentMethod: 'Card',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      SaleModel(
        id: 's4',
        billNumber: '#MD-2214',
        date: DateTime.now().subtract(const Duration(days: 2)),
        subtotal: 73000,
        discount: 2500,
        total: 70500,
        profit: 19500,
        items: [],
        paymentMethod: 'Cash',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
      SaleModel(
        id: 's5',
        billNumber: '#MD-2215',
        date: DateTime.now().subtract(const Duration(days: 3)),
        subtotal: 54000,
        discount: 1900,
        total: 52100,
        profit: 12800,
        items: [],
        paymentMethod: 'UPI',
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now(),
        isSynced: true,
      ),
    ];

    final box = HiveService.salesBox;
    for (final sale in sales) {
      await box.put(sale.id, sale);
    }
  }
}
