// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ2vTh4E-wVeA8ORYqICJ1c4V4kyYGqM8',
    appId: '1:1013441758325:web:44bd88f33ed66105aa243c',
    messagingSenderId: '1013441758325',
    projectId: 'foodsters-74219',
    authDomain: 'foodsters-74219.firebaseapp.com',
    storageBucket: 'foodsters-74219.appspot.com',
    measurementId: 'G-3FC511Q90N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS911GMbuddEWawDVIorIb_kC3rE07JRM',
    appId: '1:1013441758325:android:2dd5865d439be939aa243c',
    messagingSenderId: '1013441758325',
    projectId: 'foodsters-74219',
    storageBucket: 'foodsters-74219.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFwhWxAA_BgaB3WSOjm2JeVUta1EFU0Sc',
    appId: '1:1013441758325:ios:66a771df883ad360aa243c',
    messagingSenderId: '1013441758325',
    projectId: 'foodsters-74219',
    storageBucket: 'foodsters-74219.appspot.com',
    iosBundleId: 'com.aftab.pwa.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ2vTh4E-wVeA8ORYqICJ1c4V4kyYGqM8',
    appId: '1:1013441758325:web:8f98bd684e3e62aeaa243c',
    messagingSenderId: '1013441758325',
    projectId: 'foodsters-74219',
    authDomain: 'foodsters-74219.firebaseapp.com',
    storageBucket: 'foodsters-74219.appspot.com',
    measurementId: 'G-1Q3RHYJSTS',
  );
}
